on: workflow_dispatch
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          repository: kfranqueiro/test-monorepo
          ref: main
          path: monorepo
          sparse-checkout: |
            child
            common
      - name: Checkout child repo
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: child
          token: ${{ secrets.PAT_TOKEN }}
      - name: Copy files
        run: |
          cp -r monorepo/common child/common
          cp -r monorepo/child child
      - name: Push new files to child repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add common child
          git commit -m "Sync from monorepo"
          git push origin gh-pages
        working-directory: child
